import { TemplateConfig } from '../types/generator';

export const TEMPLATES: TemplateConfig[] = [
  {
    id: 'solo_square',
    name: 'Solo Square / PFP',
    type: 'solo',
    memberCount: 1,
    width: 1254,
    height: 1254,
    overlayUrl: '/FRAME_01_SOLO_SQUARE.png',
    photoAreas: [
      {
        id: 'member_0',
        x: 284,
        y: 190,
        width: 685,
        height: 685,
        borderRadius: 40,
      },
    ],
    textAreas: [
      {
        id: 'team_name',
        x: 228,
        y: 940,
        width: 797,
        height: 40,
        fontSize: 26,
        fontWeight: 'bold',
        color: '#B45309', // Amber / Orange tone for Team name
        alignment: 'center',
        maxFontSize: 28,
        minFontSize: 16,
        isTeamName: true,
      },
      {
        id: 'member_0_name',
        x: 228,
        y: 986,
        width: 797,
        height: 70,
        fontSize: 52,
        fontWeight: 'bold',
        color: '#1B4D3E', // Deep Hunter Green
        alignment: 'center',
        maxFontSize: 56,
        minFontSize: 24,
      },
      {
        id: 'member_0_role',
        x: 228,
        y: 1062,
        width: 797,
        height: 45,
        fontSize: 32,
        fontWeight: 'normal',
        color: '#059669', // Emerald Green
        alignment: 'center',
        maxFontSize: 34,
        minFontSize: 18,
      },
    ],
  },
  {
    id: 'solo_horizontal',
    name: 'Solo Horizontal / Card',
    type: 'solo',
    memberCount: 1,
    width: 1023,
    height: 1555,
    overlayUrl: '/FRAME_02_SOLO_HORIZONTAL.png',
    photoAreas: [
      {
        id: 'member_0',
        x: 231,
        y: 227,
        width: 561,
        height: 777,
        borderRadius: 40,
      },
    ],
    textAreas: [
      {
        id: 'team_name',
        x: 178,
        y: 1070,
        width: 665,
        height: 40,
        fontSize: 26,
        fontWeight: 'bold',
        color: '#B45309',
        alignment: 'center',
        maxFontSize: 28,
        minFontSize: 16,
        isTeamName: true,
      },
      {
        id: 'member_0_name',
        x: 178,
        y: 1120,
        width: 665,
        height: 70,
        fontSize: 52,
        fontWeight: 'bold',
        color: '#1B4D3E',
        alignment: 'center',
        maxFontSize: 56,
        minFontSize: 24,
      },
      {
        id: 'member_0_role',
        x: 178,
        y: 1198,
        width: 665,
        height: 45,
        fontSize: 32,
        fontWeight: 'normal',
        color: '#059669',
        alignment: 'center',
        maxFontSize: 34,
        minFontSize: 18,
      },
    ],
  },
  {
    id: 'team_two',
    name: 'Team — 2 Members',
    type: 'team',
    memberCount: 2,
    width: 1774,
    height: 887,
    overlayUrl: '/FRAME_03_TEAM_TWO.png',
    photoAreas: [
      {
        id: 'member_0',
        x: 296,
        y: 196,
        width: 561,
        height: 421,
        borderRadius: 25,
      },
      {
        id: 'member_1',
        x: 908,
        y: 196,
        width: 561,
        height: 421,
        borderRadius: 25,
      },
    ],
    textAreas: [
      // Member 0
      {
        id: 'member_0_team',
        x: 286,
        y: 652,
        width: 577,
        height: 30,
        fontSize: 20,
        fontWeight: 'bold',
        color: '#B45309',
        alignment: 'center',
        maxFontSize: 22,
        minFontSize: 14,
        isTeamName: true,
      },
      {
        id: 'member_0_name',
        x: 286,
        y: 688,
        width: 577,
        height: 45,
        fontSize: 36,
        fontWeight: 'bold',
        color: '#1B4D3E',
        alignment: 'center',
        maxFontSize: 40,
        minFontSize: 18,
      },
      {
        id: 'member_0_role',
        x: 286,
        y: 738,
        width: 577,
        height: 35,
        fontSize: 24,
        fontWeight: 'normal',
        color: '#059669',
        alignment: 'center',
        maxFontSize: 26,
        minFontSize: 14,
      },
      // Member 1
      {
        id: 'member_1_team',
        x: 898,
        y: 652,
        width: 577,
        height: 30,
        fontSize: 20,
        fontWeight: 'bold',
        color: '#B45309',
        alignment: 'center',
        maxFontSize: 22,
        minFontSize: 14,
        isTeamName: true,
      },
      {
        id: 'member_1_name',
        x: 898,
        y: 688,
        width: 577,
        height: 45,
        fontSize: 36,
        fontWeight: 'bold',
        color: '#1B4D3E',
        alignment: 'center',
        maxFontSize: 40,
        minFontSize: 18,
      },
      {
        id: 'member_1_role',
        x: 898,
        y: 738,
        width: 577,
        height: 35,
        fontSize: 24,
        fontWeight: 'normal',
        color: '#059669',
        alignment: 'center',
        maxFontSize: 26,
        minFontSize: 14,
      },
    ],
  },
  {
    id: 'team_three',
    name: 'Team — 3 Members',
    type: 'team',
    memberCount: 3,
    width: 1672,
    height: 941,
    overlayUrl: '/FRAME_04_TEAM_THREE.png',
    photoAreas: [
      {
        id: 'member_0',
        x: 222,
        y: 192,
        width: 377,
        height: 421,
        borderRadius: 20,
      },
      {
        id: 'member_1',
        x: 644,
        y: 192,
        width: 377,
        height: 421,
        borderRadius: 20,
      },
      {
        id: 'member_2',
        x: 1062,
        y: 192,
        width: 377,
        height: 421,
        borderRadius: 20,
      },
    ],
    textAreas: [
      // Member 0
      {
        id: 'member_0_team',
        x: 210,
        y: 648,
        width: 397,
        height: 30,
        fontSize: 18,
        fontWeight: 'bold',
        color: '#B45309',
        alignment: 'center',
        maxFontSize: 20,
        minFontSize: 12,
        isTeamName: true,
      },
      {
        id: 'member_0_name',
        x: 210,
        y: 684,
        width: 397,
        height: 45,
        fontSize: 32,
        fontWeight: 'bold',
        color: '#1B4D3E',
        alignment: 'center',
        maxFontSize: 36,
        minFontSize: 16,
      },
      {
        id: 'member_0_role',
        x: 210,
        y: 734,
        width: 397,
        height: 35,
        fontSize: 22,
        fontWeight: 'normal',
        color: '#059669',
        alignment: 'center',
        maxFontSize: 24,
        minFontSize: 12,
      },
      // Member 1
      {
        id: 'member_1_team',
        x: 630,
        y: 648,
        width: 397,
        height: 30,
        fontSize: 18,
        fontWeight: 'bold',
        color: '#B45309',
        alignment: 'center',
        maxFontSize: 20,
        minFontSize: 12,
        isTeamName: true,
      },
      {
        id: 'member_1_name',
        x: 630,
        y: 684,
        width: 397,
        height: 45,
        fontSize: 32,
        fontWeight: 'bold',
        color: '#1B4D3E',
        alignment: 'center',
        maxFontSize: 36,
        minFontSize: 16,
      },
      {
        id: 'member_1_role',
        x: 630,
        y: 734,
        width: 397,
        height: 35,
        fontSize: 22,
        fontWeight: 'normal',
        color: '#059669',
        alignment: 'center',
        maxFontSize: 24,
        minFontSize: 12,
      },
      // Member 2
      {
        id: 'member_2_team',
        x: 1048,
        y: 648,
        width: 397,
        height: 30,
        fontSize: 18,
        fontWeight: 'bold',
        color: '#B45309',
        alignment: 'center',
        maxFontSize: 20,
        minFontSize: 12,
        isTeamName: true,
      },
      {
        id: 'member_2_name',
        x: 1048,
        y: 684,
        width: 397,
        height: 45,
        fontSize: 32,
        fontWeight: 'bold',
        color: '#1B4D3E',
        alignment: 'center',
        maxFontSize: 36,
        minFontSize: 16,
      },
      {
        id: 'member_2_role',
        x: 1048,
        y: 734,
        width: 397,
        height: 35,
        fontSize: 22,
        fontWeight: 'normal',
        color: '#059669',
        alignment: 'center',
        maxFontSize: 24,
        minFontSize: 12,
      },
    ],
  },
];
